import type { Command } from 'commander';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { getContext as GetContextFn } from '../../cli.js';
import type { CliContext } from '../../types/context.js';
import { getConfigDir } from '../../platform/paths.js';

type ContextGetter = typeof GetContextFn;
type AgentTarget = 'opencode' | 'claude' | 'cursor' | 'codex' | 'generic';

type InitOptions = {
  agent: string;
  global: boolean;
  yes: boolean;
};

const START_MARKER = '<!-- TRACEBACK-SKILLS:START -->';
const END_MARKER = '<!-- TRACEBACK-SKILLS:END -->';
const SKILL_MARKER = '<!-- Generated by traceback skills init. -->';

const SKILLS: Record<string, string> = {
  'traceback-cli': `${SKILL_MARKER}
# Traceback CLI — Core Reference

Use the Traceback CLI (traceback) to interact with Traceback AI test automation, manage workspaces, and run browser/mobile tests from the terminal.

## Authentication & Account
- traceback login: Opens browser to authenticate
- traceback whoami: Show currently authenticated user
- traceback auth status: Show active session and token details
- traceback auth logout: Clear saved credentials

## Global Flags
- --json: Output pure JSON
- --ci: Non-interactive CI mode
- --silent: Suppress informational output
- --debug / -d: Verbose debug logs
`,
  'traceback-cli-tests': `${SKILL_MARKER}
# Traceback Tests Execution

Browse, trigger, and stream cloud-based browser and mobile test executions directly in the terminal.

- Interactive: traceback tests
- Non-interactive: traceback tests --test-id <test-id> --environment production --ci --json
- History: traceback runs
`,
  'traceback-cli-mobile-verify': `${SKILL_MARKER}
# Traceback Mobile Verification

Use traceback mobile verify for goal-based mobile verification against a running Android emulator or iOS simulator.

1. Run traceback setup once to install Appium and platform drivers.
2. Run traceback tests and choose Mobile tests, or run direct command:
   traceback mobile verify --goal "Log in and verify dashboard" --platform android
3. Use --device to pin a serial or UDID.
4. Keep the goal observable and specific.
`,
  'traceback-cli-emulator-selection': `${SKILL_MARKER}
# Traceback Emulator Selection

Before starting a mobile run, detect booted devices with platform-native tools:
- Android: adb devices -l
- iOS: xcrun simctl list devices booted

If one booted device is detected, use it. If multiple exist, prompt or require --device.
`,
  'traceback-cli-appium-lifecycle': `${SKILL_MARKER}
# Traceback Appium Session Lifecycle

A mobile test owns its Appium session for the duration of one run.
1. Connect or start Appium before requesting UI state.
2. Attach to target device.
3. Close the Appium session immediately upon run completion, failure, or cancellation.
4. Do not kill unrelated user sessions.
`,
  'traceback-mcp': `${SKILL_MARKER}
# Traceback MCP Server

Start the Traceback Model Context Protocol (MCP) server for AI coding agents:
- Command: traceback mcp
- Supports: Claude Code, Cursor, OpenCode, Codex, Antigravity
- Tools: list_tests, run_test, get_run_status, mobile_verify
`,
  'traceback-cli-workspaces': `${SKILL_MARKER}
# Traceback Workspaces & Projects

- traceback workspaces: Select active workspace
- traceback project list: List projects
- traceback project get <id>: Get project details
`,
  'traceback-cli-doctor': `${SKILL_MARKER}
# Traceback Doctor

Diagnose and verify local environment:
- traceback doctor: Validate token, network, Appium, and Node environment
`,
};

const AGENT_LABELS: Record<AgentTarget, string> = {
  opencode: 'OpenCode',
  claude: 'Claude Code',
  cursor: 'Cursor',
  codex: 'Codex',
  generic: 'Generic AGENTS.md',
};

export function registerSkillsCommands(program: Command, getContext: ContextGetter): void {
  const skills = program
    .command('skills')
    .description('Install and manage Traceback skills for AI agents');

  skills
    .command('init')
    .description('Initialize Traceback skills for an AI coding agent')
    .option('-a, --agent <agent>', 'Agent: opencode, claude, cursor, codex, or generic', 'auto')
    .option('--global', 'Install skills in the user-level agent configuration', false)
    .option('-y, --yes', 'Use detected/default settings without prompting', false)
    .action(async function (this: Command, options: InitOptions) {
      const ctx = getContext(this);
      if (!ctx) return;
      await initializeSkills(ctx, options);
    });

  skills
    .command('list')
    .description('List initialized Traceback skills')
    .option('--global', 'List user-level skills instead of project skills', false)
    .action(async function (this: Command, options: { global: boolean }) {
      const ctx = getContext(this);
      if (!ctx) return;
      listSkills(ctx, options.global);
    });

  skills
    .command('doctor')
    .description('Check skill files and agent adapters')
    .option('--global', 'Check user-level skills instead of project skills', false)
    .action(async function (this: Command, options: { global: boolean }) {
      const ctx = getContext(this);
      if (!ctx) return;
      doctorSkills(ctx, options.global);
    });
}

async function initializeSkills(ctx: CliContext, options: InitOptions): Promise<void> {
  const ui = ctx.infra.ui;
  const projectRoot = process.cwd();
  const target = await resolveAgentTarget(ctx, options.agent, options.yes, projectRoot);
  if (!target) return;

  const skillRoot = options.global
    ? path.join(getConfigDir(), 'skills')
    : path.join(projectRoot, '.traceback', 'skills');
  const skillReference = options.global ? skillRoot : '.traceback/skills';

  fs.mkdirSync(skillRoot, { recursive: true });
  let written = 0;
  let skipped = 0;

  for (const [name, content] of Object.entries(SKILLS)) {
    const filePath = path.join(skillRoot, name, 'SKILL.md');
    const result = writeOwnedSkill(filePath, content);
    if (result === 'written') written += 1;
    else skipped += 1;
  }

  const adapterPath = getAdapterPath(target, options.global);
  const adapterContent = getAdapterContent(target, skillReference);
  const adapterResult = upsertAdapter(adapterPath, adapterContent, target === 'cursor');

  ui.success(`Traceback skills initialized for ${AGENT_LABELS[target]}.`);
  ui.info(`Skills: ${skillRoot}`);
  ui.info(`Adapter: ${adapterPath}`);
  ui.info(
    `Installed ${written} skill${written === 1 ? '' : 's'}${skipped ? ` (${skipped} existing file${skipped === 1 ? '' : 's'} kept)` : ''}.`,
  );
  if (adapterResult === 'skipped') {
    ui.warn(`Adapter already exists and is not Traceback-managed: ${adapterPath}`);
    ui.hint('Review it manually and add the Traceback skills path if desired.');
  }
}

async function resolveAgentTarget(
  ctx: CliContext,
  requested: string,
  skipPrompt: boolean,
  projectRoot: string,
): Promise<AgentTarget | null> {
  const normalized = requested.toLowerCase() as AgentTarget | 'auto';
  if (normalized !== 'auto') {
    if (normalized in AGENT_LABELS) return normalized as AgentTarget;
    ctx.infra.ui.error(
      `Unknown agent ${requested}. Use opencode, claude, cursor, codex, or generic.`,
    );
    return null;
  }

  const detected = detectAgents(projectRoot);
  if (detected.length === 1 || skipPrompt) {
    return detected[0] ?? 'generic';
  }

  if (!ctx.flags.ci && !ctx.flags.json && !ctx.flags.silent) {
    const { select } = await import('@inquirer/prompts');
    return await select<AgentTarget>({
      message: 'Which agent should receive the Traceback skills?',
      choices: (Object.keys(AGENT_LABELS) as AgentTarget[]).map((agent) => ({
        name: `${AGENT_LABELS[agent]}${detected.includes(agent) ? ' (detected)' : ''}`,
        value: agent,
      })),
    });
  }

  return 'generic';
}

function detectAgents(projectRoot: string): AgentTarget[] {
  const detected: AgentTarget[] = [];
  if (fs.existsSync(path.join(projectRoot, '.opencode')) || process.env.OPENCODE)
    detected.push('opencode');
  if (
    fs.existsSync(path.join(projectRoot, '.claude')) ||
    fs.existsSync(path.join(projectRoot, 'CLAUDE.md'))
  ) {
    detected.push('claude');
  }
  if (fs.existsSync(path.join(projectRoot, '.cursor'))) detected.push('cursor');
  if (fs.existsSync(path.join(projectRoot, '.codex'))) detected.push('codex');
  if (fs.existsSync(path.join(projectRoot, 'AGENTS.md')) || detected.length === 0)
    detected.push('generic');
  return detected;
}

function getAdapterPath(target: AgentTarget, global: boolean): string {
  if (global) {
    const home = os.homedir();
    switch (target) {
      case 'opencode':
        return path.join(home, '.config', 'opencode', 'AGENTS.md');
      case 'claude':
        return path.join(home, '.claude', 'CLAUDE.md');
      case 'cursor':
        return path.join(home, '.cursor', 'rules', 'traceback-skills.mdc');
      case 'codex':
        return path.join(home, '.codex', 'AGENTS.md');
      default:
        return path.join(home, 'AGENTS.md');
    }
  }

  switch (target) {
    case 'claude':
      return path.join(process.cwd(), 'CLAUDE.md');
    case 'cursor':
      return path.join(process.cwd(), '.cursor', 'rules', 'traceback-skills.mdc');
    default:
      return path.join(process.cwd(), 'AGENTS.md');
  }
}

function getAdapterContent(target: AgentTarget, skillReference: string): string {
  const common = `Read the relevant Traceback skill before planning or executing a related task. Skills are guidance, not permission to access production systems or secrets.\n\nSkill directory: ${skillReference}\n\nAvailable skills:\n${Object.keys(
    SKILLS,
  )
    .map((name) => `- ${name}/SKILL.md`)
    .join('\n')}`;
  if (target === 'cursor') {
    return `---\ndescription: Traceback CLI and mobile testing skills\nalwaysApply: true\n---\n\n${common}`;
  }
  return `${START_MARKER}\n## Traceback skills\n\n${common}\n${END_MARKER}`;
}

function writeOwnedSkill(filePath: string, content: string): 'written' | 'skipped' {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, `${content.trim()}\n`, 'utf8');
    return 'written';
  }

  const existing = fs.readFileSync(filePath, 'utf8');
  if (!existing.includes(SKILL_MARKER)) return 'skipped';
  fs.writeFileSync(filePath, `${content.trim()}\n`, 'utf8');
  return 'written';
}

function upsertAdapter(
  filePath: string,
  content: string,
  replaceWholeFile: boolean,
): 'written' | 'skipped' {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, `${content.trim()}\n`, 'utf8');
    return 'written';
  }

  const existing = fs.readFileSync(filePath, 'utf8');
  if (replaceWholeFile) {
    if (
      !existing.includes(START_MARKER) &&
      !existing.includes('Traceback CLI and mobile testing skills')
    ) {
      return 'skipped';
    }
    fs.writeFileSync(filePath, `${content.trim()}\n`, 'utf8');
    return 'written';
  }

  const start = existing.indexOf(START_MARKER);
  const end = existing.indexOf(END_MARKER);
  if (start !== -1 && end !== -1 && end > start) {
    const updated = `${existing.slice(0, start)}${content.trim()}${existing.slice(end + END_MARKER.length)}`;
    fs.writeFileSync(filePath, updated, 'utf8');
    return 'written';
  }

  fs.writeFileSync(filePath, `${existing.trimEnd()}\n\n${content.trim()}\n`, 'utf8');
  return 'written';
}

function listSkills(ctx: CliContext, global: boolean): void {
  const root = global
    ? path.join(getConfigDir(), 'skills')
    : path.join(process.cwd(), '.traceback', 'skills');
  const installed = Object.keys(SKILLS).filter((name) =>
    fs.existsSync(path.join(root, name, 'SKILL.md')),
  );
  if (ctx.flags.json) {
    ctx.infra.ui.renderJson({ root, skills: installed });
    return;
  }
  if (!installed.length) {
    ctx.infra.ui.info(`No Traceback skills initialized at ${root}.`);
    ctx.infra.ui.hint('Run `traceback skills init` to install them.');
    return;
  }
  ctx.infra.ui.info(`Traceback skills at ${root}:`);
  ctx.infra.ui.table(
    ['Skill', 'Status'],
    installed.map((name) => [name, 'installed']),
  );
}

function doctorSkills(ctx: CliContext, global: boolean): void {
  const root = global
    ? path.join(getConfigDir(), 'skills')
    : path.join(process.cwd(), '.traceback', 'skills');
  const missing = Object.keys(SKILLS).filter(
    (name) => !fs.existsSync(path.join(root, name, 'SKILL.md')),
  );
  const adapterCandidates = (Object.keys(AGENT_LABELS) as AgentTarget[]).map((target) =>
    getAdapterPath(target, global),
  );
  const adapters = [...new Set(adapterCandidates.filter((filePath) => fs.existsSync(filePath)))];

  if (ctx.flags.json) {
    ctx.infra.ui.renderJson({ root, missing, adapters });
    return;
  }
  if (missing.length === 0)
    ctx.infra.ui.success(`All ${Object.keys(SKILLS).length} Traceback skills are present.`);
  else ctx.infra.ui.warn(`Missing skills: ${missing.join(', ')}`);
  if (adapters.length) ctx.infra.ui.info(`Adapters found: ${adapters.join(', ')}`);
  else ctx.infra.ui.warn('No agent adapter found. Run `traceback skills init --agent <agent>`.');
}
